export const books = [
  {
    id: 1,
    title: "Atomic Habits",
    description: "A guide to building good habits and breaking bad ones.",
    author: "James Clear",
    price: 15,
    isCompleted: false,
  },
  {
    id: 2,
    title: "Deep Work",
    description: "Rules for focused success in a distracted world.",
    author: "Cal Newport",
    price: 20,
    isCompleted: false,
  },
  {
    id: 3,
    title: "The Alchemist",
    description: "A journey of self-discovery and dreams.",
    author: "Paulo Coelho",
    price: 12,
    isCompleted: false,
  },
  {
    id: 4,
    title: "Rich Dad Poor Dad",
    description: "What the rich teach their kids about money.",
    author: "Robert Kiyosaki",
    price: 18,
    isCompleted: false,
  },
  {
    id: 5,
    title: "The Subtle Art of Not Giving a F*ck",
    description: "A counterintuitive approach to living a good life.",
    author: "Mark Manson",
    price: 14,
    isCompleted: false,
  },
  {
    id: 6,
    title: "Thinking, Fast and Slow",
    description:
      "Explores two systems of thinking: fast and intuitive vs slow and logical.",
    author: "Daniel Kahneman",
    price: 22,
    isCompleted: false,
  },
  {
    id: 7,
    title: "Start With Why",
    description: "How great leaders inspire action.",
    author: "Simon Sinek",
    price: 16,
    isCompleted: false,
  },
  {
    id: 8,
    title: "The 7 Habits of Highly Effective People",
    description: "Powerful lessons in personal change.",
    author: "Stephen R. Covey",
    price: 19,
    isCompleted: false,
  },
  {
    id: 9,
    title: "Can't Hurt Me",
    description: "Master your mind and defy the odds.",
    author: "David Goggins",
    price: 17,
    isCompleted: false,
  },
  {
    id: 10,
    title: "Man's Search for Meaning",
    description: "A Holocaust survivor's lessons for spiritual survival.",
    author: "Viktor Frankl",
    price: 13,
    isCompleted: false,
  },
];
